### ISSUE TITLE
Configure Gitlab instance

### ISSUE THREAD

**Issue by fransvdl** [benr77/obsidian-gitlab-issues#1]
Hi @benr77,

I found your plugin and would like to use it, but we have our own hosted Gitlab instance and it would be great if one could configure this in the same manner as the token. 

I started making the changes, would it be fine if I create a pull request to have this feature pulled in?

Regards,
Frans

**Comment by benr77** [comment]
Hi Frans. Yes, please do submit a PR for this - I'll happily merge it.

This feature is something I was considering doing myself, but I have actually been waiting for the Obsidian team to approve the plugin so it can be added to the community plugins system, and to become installable directly from within Obsidian. But there is no need to wait.

Thanks

**Comment by fransvdl** [comment]
That explains why it did not show up while I was searching for it in the Community Plugin list :smile:
