### ISSUE TITLE
Can't Find Plugin in Obsidian Plugin Search?

### ISSUE THREAD

**Issue by npazo** [benr77/obsidian-gitlab-issues#11]
I was looking to install this via the Obsidian UI but when I search for GitLab nothing comes up. Any thoughts?

**Comment by benr77** [comment]
Coincidentally, after waiting for several months for the application to the community plugins list to be accepted, this happened yesterday 2 hours after you opened this issue!

So I'm pleased to say that it now is available directly through the Obsidian UI.
