### ISSUE TITLE
Feature Request - support publishing to Gitlab Wiki?

### ISSUE THREAD

**Issue by bradwood** [benr77/obsidian-gitlab-issues#17]
**Is your feature request related to a problem? Please describe.**

No, arguably its for a whole new plugin!

**Describe the solution you'd like**
It would be cool to be able to publish a canvas or vault directly to a a Gitlab Wiki. Gitlab wiki's are nothing more than git repos that hold markdown, so it might be quite easy to just push the markdown up to the wiki repo.

The challenges might involve some regex work to make the rendered markdown gitlab-wiki compatible (e.g., link rewriting, etc), maybe some pandoc type stuff, etc...

**Describe alternatives you've considered**
I've not thought too much further about this,  but it could be done in a more simple way with a few shell scripts I guess.

**Additional context**
Nope

**Comment by benr77** [comment]
Thanks for your input, but I definitely agree with you that it's something for an entirely separate plugin. 

It's not something I would consider trying to add to this package.

Also, in terms of publishing there is already the [Obsidian Publish](https://obsidian.md/publish) system, and I would suggest that building anything new should also be able to support more than Gitlab as a target destination.
