### ISSUE TITLE
[API][SYNC] A user should be able to control the way issues are synced with notes.

### ISSUE THREAD

**Issue by leroycharles** [benr77/obsidian-gitlab-issues#18]
**Is your feature request related to a problem? Please describe.**
The current behavior creates the note when I created it on Gitlab.
When the issue is closed, the note is deleted.
If a note is required for history purposes it can not be kept in the vault with the current behavior.

**Describe the solution you'd like**
A setting `Update type` represented as a drop-down list with the following items and corresponding behavior:

1. `Full`, full-update (default), current behavior, note is created, updated and deleted in adequacy with the Gitlab Issue.
2. `Write-Only`, half-update, note is created and updated in adequacy with the Gitlab Issue.
3. `Once`, no-update, note is created in adequacy with the Gitlab Issue.
4. `Archive`, full-update, note is created, updated and archived (moved to another folder when closed) in adequacy with the Gitlab Issue.

**Describe alternatives you've considered**

1. Make all the update I require, revoke the token when I start closing issues (current work around).
2. Activate use the plugin when create or update an issue, then deactivate the plugin (no practical, especially since I work with a team of students, it over-complicates the note taking process)
3. Having all the note created in a "buffer" directory, then moving them to the correct location on creation/update (might implement this one for the next semester).

**Additional context**
I'm using Obsidian to take notes during my classes. Other students contributes to the note taking.
I'm using Gitlab to manage this process and deploy the notes to Gitlab Pages.

**Comment by benr77** [comment]
I'm wondering if this can be achieved using a separate plugin. I've done a quick search and found https://github.com/farux/obsidian-auto-note-mover which seems to be able to automatically move notes that have a certain tag. 

If you add a tag to your custom template file in this Gitlab Issues plugin, each issue from Gitlab will automatically be tagged, and then this Auto Note Mover plugin can detect it and automatically move it to your archived/permanent folder.

**Comment by benr77** [comment]
Closing as looks like alternative solution was sufficient. Feel free to re-open this issue if needed.
