### ISSUE TITLE
Plugin reloading multiple times

### ISSUE THREAD

**Issue by fransvdl** [benr77/obsidian-gitlab-issues#2]
Hi @benr77,

While configuring the Gitlab token the plugin is automatically reloaded for each character changed, this creates a new icon and a new refresh request for each reload.

Below is a screenshot with the icon added each reload.

![Screenshot from 2022-09-25 11-52-58](https://user-images.githubusercontent.com/583184/192138022-05df5886-a551-4299-93af-be751b35d924.png)

Regards,
Frans

**Comment by benr77** [comment]
Great stuff thanks
